export const ALLERGIES = [
  // Seasonal / Environmental
  "Pollen (Seasonal Allergies)",
  "Dust Mites",
  "Mold Spores",
  "Ragweed",
  "Grass Pollen",
  "Tree Pollen",
  "Pet Dander (Dogs)",
  "Pet Dander (Cats)",
  "Cockroach Droppings",
  "Feathers",
  // Food
  "Peanuts",
  "Tree Nuts",
  "Dairy (Milk)",
  "Eggs",
  "Gluten / Wheat",
  "Shellfish",
  "Fish",
  "Soy",
  "Sesame",
  // Other
  "Latex",
  "Insect Stings (Bees, Wasps)",
  "Medication (Penicillin)",
  "Medication (Sulfa)",
  "Smoke / Air Pollution",
  "Perfumes / Fragrances",
  "Cleaning Products",
  "Nickel (Metals)",
  "Sunlight (Photosensitivity)",
];

export const SKIN_ISSUES = [
  "Dry / Cracked Skin (Cold Weather)",
  "Eczema Flare-Ups",
  "Heat Rash (Prickly Heat)",
  "Sunburn / UV Sensitivity",
  "Chapped Lips",
  "Cold Urticaria (Hives from Cold)",
  "Rosacea (Triggered by Sun/Heat)",
  "Photosensitivity",
  "Contact Dermatitis (Plants)",
  "Acne (Worsened by Humidity)",
  "Frostnip / Frostbite Sensitivity",
  "Windburn",
  "Hives (Temperature Changes)",
];

export const HEALTH_CONCERNS = [
  "Heat Exhaustion / Heat Stroke",
  "Cold Sensitivity",
  "Asthma (Cold Air Triggered)",
  "Asthma (Humidity Triggered)",
  "Asthma (Poor Air Quality)",
  "Migraines (Weather Changes)",
  "Joint Pain (Barometric Pressure)",
  "Sinus Issues (Air Pressure Changes)",
  "Seasonal Allergy Symptoms",
  "Respiratory Issues (Air Quality)",
  "Cardiovascular (Heat Sensitivity)",
  "Dehydration Risk",
  "Raynaud's Phenomenon (Cold)",
  "Chronic Fatigue (Weather Related)",
  "Mood Changes (Seasonal Affective)",
  "Sleep Disruption (Temperature)",
];
